Added element screenshot functionality
devbridge/test-juggler pull request #76
Opened 2020-11-03 14:52 UTC by jevgenijusmarinuskinas

2020-11-03 14:59 UTC, Martynienas commented
Refactor  test "should capture screenshot of specific page element" under VisualRegression.test.js to use the new functionality

2020-11-03 15:01 UTC, Martynienas requested changes
Refactor test "should capture screenshot of specific page element" under VisualRegression.test.js to use the new functionality

2020-11-03 15:05 UTC, jevgenijusmarinuskinas commented
> Refactor test "should capture screenshot of specific page element" under VisualRegression.test.js to use the new functionality

Fixed, moved and refactored to VisualRegression.test.js

2020-11-06 11:04 UTC, Martynienas approved these changes

2020-11-06 11:39 UTC, merged